"""init

Revision ID: f57b627352c9
Revises: 2f28b7d0e670
Create Date: 2023-03-13 15:06:50.385436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f57b627352c9'
down_revision = '2f28b7d0e670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=False))
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
